# tests/make_signing_vectors.py
"""Regenerate tests/fixtures/signing_vectors.json.

RE-RUNNABLE AND COMMITTED, following this repo's make_*_subset.py precedent: a fixture
nobody can regenerate is a fixture nobody can check.

WHAT THESE VECTORS ARE FOR, stated precisely because it is easy to over-read. They are
generated by the encoder they check, so they CANNOT establish that the format is
correct -- only that it has not drifted. Correctness rests on the property tests in
tests/test_signing_payload.py plus review of the format itself.

What they add is INDEPENDENT CHECKABILITY: each case stores the payload as an escaped
JSON string beside its digest, so a reviewer can read the payload by eye and confirm the
digest with `sha256sum` without running any drugref code. That is also exactly what a
third party reimplementing the format in another language needs.

THE TEST KEY IS 32 BYTES OF 00..1f -- obviously not a real key, and never registered in
any database. Ed25519 is deterministic, so its signatures are reproducible and committable.

Run:  uv run python -m tests.make_signing_vectors > tests/fixtures/signing_vectors.json
"""
import json

from drugref import releases, signing

TEST_PRIVATE = bytes(range(32))


def _cases(fp: str) -> list[dict]:
    """The four vectors, each earning its place by showing something the property
    tests in test_signing_payload.py cannot show together (see module docstring there
    for what those tests already prove in isolation).

    Field lists below are written in signing.FIELD_LISTS' FROZEN ORDER for their
    context, and each case supplies every field in that list -- these vectors are the
    format's published reference, so an incomplete row would publish a wrong example.
    """
    # Case 1 and case 2's fields are built here, not inline below, because case 3's
    # manifest entries reuse them: a manifest's payload_digest is the digest of the ROW
    # it describes, so pointing case 3 at these two judgements' real payloads (rather
    # than an arbitrary placeholder digest) makes the fixture describe something
    # internally consistent, the way an actual release_manifest would.
    interaction_fields = [
        # Case 1: a realistic, fully-graded row. It plants a NULL (question_uuid) next
        # to fourteen present fields, so a reviewer can see the "N" tag beside "S" tags
        # in one payload rather than only in the isolated single-field property tests
        # above. It also carries a `mechanism` value containing both a newline and a
        # colon -- the two characters the encoding itself uses as punctuation -- which
        # is what makes the committed payload demonstrate that LENGTH-PREFIXING, not
        # delimiter-scanning, is what a parser must do: a naive line-or-colon-split
        # parser would misparse this exact case.
        ["subject_moiety_uuid", "3f7a1c22-0b64-5e9d-9a11-8c4f2e6b0d13"],
        ["object_class_uuid", "c1d9e04a-7b23-5f18-8e6c-2a90d4f7b155"],
        ["relationship", "CI_PE"],
        ["applies", "true"],
        ["severity", "major"],
        ["mechanism",
         "additive anticoagulant effect:\nplatelet inhibition also contributes"],
        ["management", "monitor INR; consider dose reduction"],
        ["evidence_grade", "established"],
        ["question_uuid", None],
        ["source", "DRUGREF"],
        ["reviewed_by", "a curator"],
        ["reviewed_against", "MED-RT 2026.07.06"],
        ["reviewed_at", "2026-08-09T04:31:07.123456Z"],
        ["signer_key_fingerprint", fp],
        ["signed_at", "2026-08-09T04:33:52.008117Z"],
    ]
    condition_fields = [
        # Case 2: a RETIRING ruling -- a curator has decided the pairing never should
        # have been asserted, so four of the grading fields (severity, mechanism,
        # management, evidence_grade) are NULL together. This is the shape a
        # delimiter-scanning parser would find easiest to get right (lots of adjacent
        # "empty" fields) and the shape most likely to hide an off-by-one in a
        # length-prefixed parser (four consecutive zero-length runs), so it earns its
        # place by being the opposite extreme from case 1's single NULL among fifteen
        # fields. question_uuid is populated here (unlike case 1), so between the two
        # cases both the "N" and "S" spelling of that field are on the record.
        ["subject_moiety_uuid", "9b1f4a6e-2c3d-5e7f-a1b2-c3d4e5f6a7b8"],
        ["object_condition_uuid", "1a2b3c4d-5e6f-5789-9abc-def012345678"],
        ["ruling", "spurious"],
        ["severity", None],
        ["mechanism", None],
        ["management", None],
        ["evidence_grade", None],
        ["question_uuid", "2c4e6a81-0b3d-5f79-8e12-4a6c8e0b2d4f"],
        ["source", "DRUGREF"],
        ["reviewed_by", "a second curator"],
        ["reviewed_against", "post-hoc literature review 2026-08"],
        ["reviewed_at", "2026-08-10T02:15:00.000000Z"],
        ["signer_key_fingerprint", fp],
        ["signed_at", "2026-08-10T02:16:41.500000Z"],
    ]
    # Case 4: THE SAME judgement as case 1, rebuilt the way a MANIFEST ENTRY's digest is
    # -- the two attestation fields replaced by the entry sentinel pair. An entry attests
    # CONTENT, never an attestation, so it names no signer (`signer_key_fingerprint` is a
    # present EMPTY STRING, not a NULL: the field is there, it just identifies nobody)
    # and no moment (`signed_at` is releases.ENTRY_DIGEST_SIGNED_AT, the fixed 1970
    # sentinel every entry digest in every manifest is built under, forever).
    #
    # BOTH VALUES ARE READ FROM THE PRODUCTION CONSTANTS, never typed here, which is the
    # whole point of the case: `ENTRY_DIGEST_SIGNED_AT` is a frozen wire constant that
    # nothing used to read, so changing `1970-01-01` left the suite green while silently
    # invalidating every manifest ever published. Regenerate this file after such a
    # change and the committed bytes move; do not regenerate and
    # test_the_entry_digest_sentinel_is_pinned_by_a_published_vector goes red. Either way
    # the change stops being silent.
    #
    # It also publishes, checkable by eye and by sha256sum, the exact bytes a third party
    # must reproduce to confirm ONE manifest entry -- which case 3 references as a digest
    # but never spells out.
    entry_digest_fields = [
        [name, value] for name, value in interaction_fields
        if name not in signing.ATTESTATION_FIELDS
    ] + [
        ["signer_key_fingerprint", ""],
        ["signed_at", signing.render(releases.ENTRY_DIGEST_SIGNED_AT)],
    ]

    interaction_payload = signing.canonical_payload(
        "curated_interaction/v1", [(n, v) for n, v in interaction_fields])
    condition_payload = signing.canonical_payload(
        "curated_condition/v1", [(n, v) for n, v in condition_fields])

    return [
        {
            "name": "an applying interaction judgement, fully graded",
            "context": "curated_interaction/v1",
            "fields": interaction_fields,
        },
        {
            "name": "a retiring condition ruling, ungraded",
            "context": "curated_condition/v1",
            "fields": condition_fields,
        },
        {
            "name": "a manifest ENTRY digest over case 1's judgement",
            "context": "curated_interaction/v1",
            "fields": entry_digest_fields,
        },
        {
            # Case 3: the only case exercising groups (spec 5.5) -- a release manifest
            # with two `--entries--` and two `--upstream--` members. Both groups'
            # members are listed here in REVERSE of the order canonical_payload will
            # sort them into (entries: interaction before condition; upstream: MED-RT
            # before GSRS), so the fixture ITSELF is evidence the sort ran: if the
            # committed payload matched this source order, that would mean the sort
            # was a no-op or absent, not that it worked.
            #
            # Entry members carry target_kind, natural_key, payload_context,
            # payload_digest -- NOT target_id (spec 5.5, corrected in review). target_id
            # is a database-local GENERATED ALWAYS AS IDENTITY value; signing it would
            # mean a node that rebuilt rather than restored its database could never
            # match a manifest entry back to its row. natural_key is each row's own
            # immortal/deterministic key instead: the interaction's is its
            # (subject_moiety_uuid, object_class_uuid, relationship) triple, the
            # condition's its (subject_moiety_uuid, object_condition_uuid) pair,
            # slash-joined -- and each entry's payload_digest is the REAL digest of the
            # matching case above, not a placeholder, so this manifest genuinely
            # describes the two judgements this fixture also publishes.
            "name": "a release manifest with two entries and two upstream releases",
            "context": "release_manifest/v1",
            "fields": [
                ["release_tag", "2026.08.10"],
                ["published_by", "release bot"],
                ["published_at", "2026-08-10T03:00:00.000000Z"],
                ["entry_count", "2"],
                ["upstream_count", "2"],
                ["signer_key_fingerprint", fp],
                ["signed_at", "2026-08-10T03:00:05.250000Z"],
            ],
            "groups": [
                {
                    "name": "entries",
                    "members": [
                        # listed interaction-then-condition: REVERSE of sorted order
                        # (condition's target_kind is the shorter, lexicographically
                        # earlier string, so it sorts first).
                        [
                            ["target_kind", "curated_interaction"],
                            ["natural_key",
                             "3f7a1c22-0b64-5e9d-9a11-8c4f2e6b0d13/"
                             "c1d9e04a-7b23-5f18-8e6c-2a90d4f7b155/CI_PE"],
                            ["payload_context", "curated_interaction/v1"],
                            ["payload_digest", signing.digest(interaction_payload).hex()],
                        ],
                        [
                            ["target_kind", "curated_condition"],
                            ["natural_key",
                             "9b1f4a6e-2c3d-5e7f-a1b2-c3d4e5f6a7b8/"
                             "1a2b3c4d-5e6f-5789-9abc-def012345678"],
                            ["payload_context", "curated_condition/v1"],
                            ["payload_digest", signing.digest(condition_payload).hex()],
                        ],
                    ],
                },
                {
                    "name": "upstream",
                    "members": [
                        # listed MED-RT-then-GSRS: REVERSE of sorted order ("GSRS" <
                        # "MED-RT" lexicographically, so GSRS sorts first).
                        [
                            ["source", "MED-RT"],
                            ["writer", "association"],
                            ["release", "2026.07.06"],
                        ],
                        [
                            ["source", "GSRS"],
                            ["writer", "load"],
                            ["release", "2026.08.01"],
                        ],
                    ],
                },
            ],
        },
    ]


def build() -> dict:
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
    public = Ed25519PrivateKey.from_private_bytes(TEST_PRIVATE).public_key(
        ).public_bytes_raw()
    fp = signing.fingerprint(public)
    cases = []
    for case in _cases(fp):
        fields = [(n, v) for n, v in case["fields"]]
        groups = [(g["name"], [[(n, v) for n, v in m] for m in g["members"]])
                  for g in case.get("groups", [])]
        payload = signing.canonical_payload(case["context"], fields, groups)
        cases.append({**case,
                      "payload": payload.decode("utf-8"),
                      "digest": signing.digest(payload).hex(),
                      "signature": signing.sign(TEST_PRIVATE, payload).hex()})
    return {"format": "drugref-sig-v1",
            "note": ("Generated by tests/make_signing_vectors.py. These detect DRIFT, "
                     "not incorrectness -- the generator is the encoder under test. "
                     "`payload` is checkable by eye and `digest` with sha256sum."),
            "test_private_key": TEST_PRIVATE.hex(),
            "test_public_key": public.hex(),
            "test_key_fingerprint": fp,
            "cases": cases}


if __name__ == "__main__":
    print(json.dumps(build(), indent=2))
