"""Render the DrugCentral `ddi` measurement as Markdown.

Split out of ``tools/drugcentral_ddi_spike.py`` for the reason CLAUDE.md rule 4
gives -- one file, one job -- and for a second reason specific to a measurement:
rendering is **pure**. Every figure arrives in the context mapping, so this module
cannot accidentally consult the database or the dump and quietly introduce a number
the measurement phase never produced.

The precedent is ``tools/pregnancy_lactation_report.py``, which does the same for
that spike.
"""
from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any


def _resolution_table(name_only: Mapping[str, Any], cascade: Mapping[str, Any]) -> str:
    """The comparison that IS the finding: name matching vs. the structural cascade."""
    rows = [
        ("distinct endpoint names", name_only["names"], cascade["names"]),
        ("names resolved to a moiety",
         name_only["names_resolved"], cascade["names_resolved"]),
        ("rows with an unresolvable endpoint", name_only["unresolvable_rows"],
         cascade["unresolvable_rows"]),
        ("distinct unordered moiety pairs", name_only["pairs"], cascade["pairs"]),
        ("pairs drugref already holds", name_only["held"], cascade["held"]),
        ("pairs that are NEW", name_only["new"], cascade["new"]),
    ]
    out = ["| measure | name matching (issue #101) | + InChIKey/CAS cascade | delta |",
           "|---|---:|---:|---:|"]
    for label, before, after in rows:
        delta = after - before
        out.append(f"| {label} | {before:,} | {after:,} | {delta:+,} |")
    return "\n".join(out)


def _routes(cascade: Mapping[str, Any]) -> str:
    out = ["| route | endpoint names |", "|---|---:|"]
    for route, count in sorted(cascade["routes"].items(), key=lambda kv: -kv[1]):
        out.append(f"| `{route}` | {count:,} |")
    return "\n".join(out)


def _references(context: Mapping[str, Any]) -> str:
    """Rule 6, printed from the `reference` table rather than inferred."""
    out = ["| `ddi_ref_id` | rows | what the dump says it is | rule 6 |",
           "|---|---:|---|---|"]
    distribution = sorted(context["ref_distribution"].items(), key=lambda kv: -kv[1])
    for ref_id, rows in distribution:
        ref = context["references"].get(ref_id, {})
        title = ref.get("title") or "(not present in the reference table)"
        who = ref.get("authors") or ""
        extra = []
        if ref.get("isbn10"):
            extra.append(f"ISBN {ref['isbn10']}")
        if ref.get("dp_year"):
            extra.append(str(ref["dp_year"]))
        detail = title
        if who:
            detail += f" — {who}"
        if extra:
            detail += f" ({', '.join(extra)})"
        verdict = "**clean — bundle**" if ref_id == "2" else "**out**"
        out.append(f"| `{ref_id}` | {rows:,} | {detail} | {verdict} |")
    return "\n".join(out)


def _qt(context: Mapping[str, Any]) -> str:
    lines = []
    for row in context["qt_rows"]:
        lines.append(
            f"- `ddi_ref_id={row['ddi_ref_id']}` · risk `{row['ddi_risk']}`\n"
            f"  - `drug_class1` = `{row['drug_class1']}`\n"
            f"  - `drug_class2` = `{row['drug_class2']}`\n"
            f"  - description: {row['description']}"
        )
    return "\n".join(lines) if lines else "_none_"


def render_report(context: Mapping[str, Any]) -> str:
    """Return the whole Markdown report for *context*."""
    whole_n, whole_c = context["whole_name_only"], context["whole_cascade"]
    bund_n, bund_c = context["bundleable_name_only"], context["bundleable_cascade"]
    totals = context["registry_totals"]
    counts: Mapping[str, int] = context["table_counts"]

    unresolved: Sequence[str] = bund_c["unresolved_names"]
    unresolved_list = "\n".join(f"- `{n}`" for n in unresolved) or "_none_"

    candidate_line = (
        f"| `ddi_candidate_pair` | {context['candidate_rows']:,} rows"
        f" · {context['candidate_pairs']:,} distinct unordered pairs |")
    risk_rows = "\n".join(
        f"| `{label}` | {context['risk_whole'].get(label, 0):,}"
        f" | {context['risk_bundleable'].get(label, 0):,} |"
        for label in sorted(context["risk_whole"]))
    table_sizes = " · ".join(f"`{t}` {c:,}" for t, c in sorted(counts.items()))

    return f"""# DrugCentral `ddi` — re-measurement for issue #101

> Generated by `tools/drugcentral_ddi_spike.py` on **{context['generated']}**.
> Re-run it rather than quoting these numbers from memory.

## What was measured, and against what

| | |
|---|---|
| dump | `{context['dump']}` |
| published release | **{context['release']}** (2023-11-01, `dbversion` 54) |
| size | {context['dump_bytes']:,} bytes |
| SHA-256 | `{context['dump_sha256']}` |
| drugref schema | `{totals['migration']}` |
| registry | {totals['moieties']:,} moieties · {totals['classes']:,} classes |
{candidate_line}

Extracted table sizes: {table_sizes}.

## Rule 6 — read from the `reference` table, never inferred

DrugCentral publishes the compilation under CC BY-SA 4.0, **which is not evidence of
a right to relicense a third-party compendium inside it.** Every `ddi` row cites one
of three references, and two of them are exactly that:

{_references(context)}

**Bundle `ddi_ref_id = 2` only.**

## Severity vocabulary

`ddi_risk` is a lookup table scoped **per reference**, so the vocabulary available to
the bundleable subset is narrower than the table's overall vocabulary:

| risk label | whole table | bundleable subset |
|---|---:|---:|
{risk_rows}

## ⇒ The finding: resolution should key on STRUCTURE, not on spelling

Issue #101 resolved endpoints by matching `substance_moiety.display_name` and
concluded the residual INN spellings *"need a synonym bridge"*. They do not:
DrugCentral resolves its own endpoint text to a `struct_id`, and `structures`
carries an InChIKey and a CAS number that drugref already holds as
`identity_claim` rows.

**Bundleable subset (`ddi_ref_id = 2`, {bund_c['rows']:,} rows):**

{_resolution_table(bund_n, bund_c)}

Routes that answered, cascade run:

{_routes(bund_c)}

**Whole table ({whole_c['rows']:,} rows), for comparison with the original evaluation:**

{_resolution_table(whole_n, whole_c)}

### The {len(unresolved)} endpoint names the cascade still cannot resolve

{unresolved_list}

## Issue 93 (QT) — restated, and narrower than recorded

`pharma_class` holds {counts.get('pharma_class', 0):,} rows and the string `QT`
appears in **{context['pharma_class_qt']}** of their names, so the dump names those
populations and defines them nowhere. The rows that mention QT at all, verbatim:

{_qt(context)}
"""
